-- Puzzle assets (secret images) and the movie catalog behind the Movies bucket.
--
-- Same access model as the init migration: the browser never touches these tables. The server
-- authorizes each request and reads them with the service role. RLS is on with no policies, so the
-- public (anon/publishable) key can read nothing here.

-- ---------------------------------------------------------------------------------------------
-- Puzzle assets: images that belong to one puzzle and must stay secret until the game shows them.
-- Served only by GET /api/assets/[id], and only when the asset id appears in the caller's current
-- play view for that game and date (puzzle, state or reveal). Bytes are re-encoded by the content
-- pipeline (metadata stripped, size capped) before they are stored.
-- ---------------------------------------------------------------------------------------------

create table public.puzzle_assets (
  id          uuid primary key default gen_random_uuid(),
  game_id     text not null,
  puzzle_date date not null,
  -- What the asset is to its game, e.g. 'frame', 'palette', 'barcode'. Free-form per game.
  kind        text not null check (char_length(kind) <= 40 and kind ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  mime        text not null check (mime in ('image/webp', 'image/jpeg', 'image/png', 'image/avif')),
  width       integer not null check (width between 1 and 8192),
  height      integer not null check (height between 1 and 8192),
  bytes       bytea not null check (octet_length(bytes) between 1 and 4194304),
  created_at  timestamptz not null default now(),
  -- Assets live and die with their puzzle. A puzzle that has plays can't be deleted (plays
  -- reference it with ON DELETE RESTRICT), so assets of a played puzzle can't vanish either.
  foreign key (game_id, puzzle_date) references public.puzzles (game_id, puzzle_date) on delete cascade
);

create index puzzle_assets_puzzle_idx on public.puzzle_assets (game_id, puzzle_date);

alter table public.puzzle_assets enable row level security;
-- No policies: only the service role may read or write assets.

-- ---------------------------------------------------------------------------------------------
-- Movie catalog: films, people (cast) and who appeared in what. Built by the content pipeline
-- (Wikidata, CC0). Read by the server for autocomplete and for resolving moves (GameServices).
-- ---------------------------------------------------------------------------------------------

create extension if not exists pg_trgm with schema extensions;
create extension if not exists unaccent with schema extensions;

-- Search normal form: lowercase, accents removed, every run of non-alphanumerics collapsed to one
-- space. "Amélie", "AMELIE" and "amelie!" all become 'amelie'; "WALL·E" becomes 'wall e'.
-- unaccent() is only STABLE because its dictionary could in principle change; we pin the
-- dictionary explicitly and treat it as immutable so the key can be a stored generated column.
create function public.catalog_search_key(value text)
returns text
language sql
immutable
strict
parallel safe
set search_path = ''
as $$
  select btrim(regexp_replace(lower(extensions.unaccent('extensions.unaccent'::regdictionary, value)), '[^[:alnum:]]+', ' ', 'g'));
$$;

create table public.movie_films (
  id          integer generated by default as identity primary key,
  title       text not null check (char_length(btrim(title)) between 1 and 300),
  year        smallint check (year between 1870 and 2100),
  -- Display-ready genre names ('Drama', 'Science fiction'), most specific first.
  genres      text[] not null default '{}' check (array_position(genres, null) is null),
  -- Director display names, credited order.
  directors   text[] not null default '{}' check (array_position(directors, null) is null),
  -- Relative fame within the catalog (higher = better known). Ranks autocomplete and picks answers.
  popularity  real not null default 0 check (popularity >= 0),
  tmdb_id     integer unique check (tmdb_id > 0),
  imdb_id     text unique check (imdb_id ~ '^tt[0-9]{7,10}$'),
  wikidata_id text unique check (wikidata_id ~ '^Q[1-9][0-9]*$'),
  search_key  text generated always as (public.catalog_search_key(title)) stored
);

create index movie_films_search_trgm_idx on public.movie_films using gin (search_key extensions.gin_trgm_ops);
create index movie_films_popularity_idx on public.movie_films (popularity desc);

create table public.movie_people (
  id          integer generated by default as identity primary key,
  name        text not null check (char_length(btrim(name)) between 1 and 200),
  popularity  real not null default 0 check (popularity >= 0),
  wikidata_id text unique check (wikidata_id ~ '^Q[1-9][0-9]*$'),
  search_key  text generated always as (public.catalog_search_key(name)) stored
);

create index movie_people_search_trgm_idx on public.movie_people using gin (search_key extensions.gin_trgm_ops);
create index movie_people_popularity_idx on public.movie_people (popularity desc);

-- Cast credits. `billing` is the cast-list position (0 = top billed) when known.
create table public.movie_credits (
  film_id   integer not null references public.movie_films (id) on delete cascade,
  person_id integer not null references public.movie_people (id) on delete cascade,
  billing   smallint check (billing >= 0),
  primary key (film_id, person_id)
);

create index movie_credits_person_idx on public.movie_credits (person_id);

alter table public.movie_films enable row level security;
alter table public.movie_people enable row level security;
alter table public.movie_credits enable row level security;
-- No policies: the server reads the catalog with the service role after checking the caller.

-- ---------------------------------------------------------------------------------------------
-- Autocomplete. Matches are tiered (exact; prefix of the title or of any word in it, so a leading
-- "The" doesn't bury a film; substring; then typo-tolerant trigram word similarity for queries of
-- 4+ characters) and ranked by popularity within a tier (by similarity first in the typo tier).
-- All tiers are served by the trigram GIN indexes above.
-- ---------------------------------------------------------------------------------------------

create function public.search_films(p_query text, p_limit integer default 8)
returns table (id integer, title text, year smallint, directors text[], popularity real)
language sql
stable
set search_path = ''
as $$
  with q as (select public.catalog_search_key(p_query) as k),
  hits as (
    select
      f.*,
      case
        when f.search_key = q.k then 0
        when f.search_key like q.k || '%' or f.search_key like '% ' || q.k || '%' then 1
        when f.search_key like '%' || q.k || '%' then 2
        else 3
      end as tier,
      extensions.word_similarity(q.k, f.search_key) as sim
    from public.movie_films f, q
    where q.k <> ''
      and (
        f.search_key like '%' || q.k || '%'
        or (char_length(q.k) >= 4 and q.k operator(extensions.<%) f.search_key)
      )
  )
  select h.id, h.title, h.year, h.directors, h.popularity
  from hits h
  order by h.tier, case when h.tier = 3 then h.sim end desc nulls last, h.popularity desc, h.id
  limit least(greatest(coalesce(p_limit, 8), 1), 25);
$$;

create function public.search_people(p_query text, p_limit integer default 8)
returns table (id integer, name text, popularity real, known_for text)
language sql
stable
set search_path = ''
as $$
  with q as (select public.catalog_search_key(p_query) as k),
  hits as (
    select
      p.id,
      p.name,
      p.popularity,
      case
        when p.search_key = q.k then 0
        when p.search_key like q.k || '%' or p.search_key like '% ' || q.k || '%' then 1
        when p.search_key like '%' || q.k || '%' then 2
        else 3
      end as tier,
      extensions.word_similarity(q.k, p.search_key) as sim
    from public.movie_people p, q
    where q.k <> ''
      and (
        p.search_key like '%' || q.k || '%'
        or (char_length(q.k) >= 4 and q.k operator(extensions.<%) p.search_key)
      )
  ),
  top as (
    select *
    from hits
    order by tier, case when tier = 3 then sim end desc nulls last, popularity desc, id
    limit least(greatest(coalesce(p_limit, 8), 1), 25)
  )
  -- Their best-known film, to tell namesakes apart in the dropdown.
  select t.id, t.name, t.popularity, k.title as known_for
  from top t
  left join lateral (
    select f.title
    from public.movie_credits c
    join public.movie_films f on f.id = c.film_id
    where c.person_id = t.id
    order by f.popularity desc, f.id
    limit 1
  ) k on true
  order by t.tier, case when t.tier = 3 then t.sim end desc nulls last, t.popularity desc, t.id;
$$;

revoke execute on function public.search_films(text, integer) from public, anon, authenticated;
revoke execute on function public.search_people(text, integer) from public, anon, authenticated;
grant execute on function public.search_films(text, integer) to service_role;
grant execute on function public.search_people(text, integer) to service_role;
